/**
 * App.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Root component. Handles:
 *  • LanguageProvider (wraps entire app — must be outermost non-native wrapper)
 *  • First-launch disclaimer (AsyncStorage flag, language-aware)
 *  • Navigation stack (React Navigation)
 *  • Status bar configuration
 *
 * Provider order (outermost → innermost):
 *   LanguageProvider          ← language state & AsyncStorage persistence
 *     NavigationContainer     ← screen routing
 *       DisclaimerModal       ← first-launch gate (reads language context)
 *         Stack.Navigator
 * ─────────────────────────────────────────────────────────────────────────────
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  View, Text, Modal, TouchableOpacity, StyleSheet,
  Animated, ScrollView, Platform, StatusBar,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { NavigationContainer, DefaultTheme } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { LinearGradient } from 'expo-linear-gradient';
import * as SplashScreen from 'expo-splash-screen';
import * as Haptics from 'expo-haptics';

import HomeScreen    from './screens/HomeScreen';
import ResultScreen  from './screens/ResultScreen';
import HistoryScreen from './screens/HistoryScreen';
import UpgradeScreen from './screens/UpgradeScreen';
import AboutScreen from './screens/AboutScreen';
import DisclaimerScreen from './screens/DisclaimerScreen';
import { COLORS, FONTS, SPACING } from './constants/theme';

// ── NEW: Language system ───────────────────────────────────────────────────────
import { LanguageProvider, useText } from './context/LanguageContext';

SplashScreen.preventAutoHideAsync().catch(() => {});

const Stack = createNativeStackNavigator();

// ─── Navigation theme ─────────────────────────────────────────────────────────

const NAV_THEME = {
  ...DefaultTheme,
  dark: true,
  colors: {
    ...DefaultTheme.colors,
    background: COLORS.background,
    card:       COLORS.surface,
    text:       COLORS.text,
    border:     COLORS.goldDim,
    primary:    COLORS.gold,
  },
};

// ─── Bilingual disclaimer content ─────────────────────────────────────────────

const DISCLAIMER_CONTENT = {
  zh: {
    title:       '易鉴 I-Ching Oracle',
    subtitle:    '开始之前',
    heading:     '⚠ 重要声明',
    intro:       '易鉴占卜应用仅供',
    introBold:   '娱乐、思考和个人冥想之用。',
    introMid:    '\n\n本应用生成的解读',
    introBoldNo: '不',
    introEnd:    '构成任何专业建议，包括但不限于：',
    bullets:     ['医疗或精神科建议', '法律或财务指导', '投资建议', '心理咨询', '宗教或灵性指导'],
    footer:      '在做出影响您健康、安全、法律地位或财务状况的决定时，请始终咨询合格的专业人士。',
    aboutTitle:  '关于《易经》',
    aboutBody:   '《易经》是世界上最古老的占卜文献之一，起源于3000多年前的中国。数千年来，它一直被用作反思、辅助决策和哲学探究的工具。\n\n本应用采用传统的"三枚铜钱法"模拟占卜过程。结果由概率决定，并非预先设定。',
    ctaButton:   '我已了解 — 开始占卜',
    ctaNote:     '继续使用即表示您确认本应用仅供娱乐之用。',
  },
  en: {
    title:       '易鉴 I-Ching Oracle',
    subtitle:    'Before we begin',
    heading:     '⚠ Important Notice',
    intro:       'The I-Ching Oracle app is designed ',
    introBold:   'for entertainment, reflection, and personal contemplation only.',
    introMid:    '\n\nReadings generated by this application do ',
    introBoldNo: 'not',
    introEnd:    ' constitute professional advice of any kind — including but not limited to:',
    bullets:     ['Medical or psychiatric advice', 'Legal or financial guidance', 'Investment recommendations', 'Psychological counseling', 'Religious or spiritual instruction'],
    footer:      'Always consult qualified professionals for decisions affecting your health, safety, legal standing, or financial wellbeing.',
    aboutTitle:  'About the I Ching',
    aboutBody:   'The I Ching (易经, "Book of Changes") is one of the world\'s oldest divination texts, originating in China over 3,000 years ago. It has been used across millennia as a tool for reflection, decision-support, and philosophical inquiry.\n\nThis app implements the traditional "Three Coin Method" (三枚铜钱法) to simulate the casting process. Results are mathematically probabilistic, not predetermined.',
    ctaButton:   'I Understand — Begin',
    ctaNote:     'By continuing, you acknowledge this is for entertainment purposes only.',
  },
};

const DISCLAIMER_KEY = '@iching_oracle:disclaimer_accepted_v1';

// ─── DisclaimerModal — language-aware ────────────────────────────────────────

function DisclaimerModal({ visible, onAccept }) {
  const fadeAnim  = useRef(new Animated.Value(0)).current;
  const slideAnim = useRef(new Animated.Value(60)).current;

  // Reads from LanguageProvider (this component is inside it)
  const { isZh } = useText();
  const c = isZh ? DISCLAIMER_CONTENT.zh : DISCLAIMER_CONTENT.en;

  useEffect(() => {
    if (visible) {
      Animated.parallel([
        Animated.timing(fadeAnim,  { toValue: 1, duration: 500, useNativeDriver: true }),
        Animated.spring(slideAnim, { toValue: 0, tension: 70, friction: 10, useNativeDriver: true }),
      ]).start();
    }
  }, [visible]);

  const handleAccept = useCallback(async () => {
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    Animated.parallel([
      Animated.timing(fadeAnim,  { toValue: 0, duration: 300, useNativeDriver: true }),
      Animated.timing(slideAnim, { toValue: 40, duration: 300, useNativeDriver: true }),
    ]).start(() => onAccept());
  }, [onAccept]);

  return (
    <Modal visible={visible} transparent animationType="none" statusBarTranslucent>
      <View style={dStyles.backdrop}>
        <Animated.View
          style={[dStyles.sheet, { opacity: fadeAnim, transform: [{ translateY: slideAnim }] }]}
        >
          <View style={dStyles.sheetHeader}>
            <Text style={dStyles.sheetIcon}>☯</Text>
            <Text style={dStyles.sheetTitle}>{c.title}</Text>
            <Text style={dStyles.sheetSubtitle}>{c.subtitle}</Text>
          </View>

          <ScrollView style={dStyles.sheetScroll} showsVerticalScrollIndicator={false}>
            <View style={dStyles.disclaimerBlock}>
              <Text style={dStyles.disclaimerHeading}>{c.heading}</Text>
              <Text style={dStyles.disclaimerBody}>
                {c.intro}
                <Text style={dStyles.disclaimerEmphasis}>{c.introBold}</Text>
                {c.introMid}
                <Text style={dStyles.disclaimerEmphasis}>{c.introBoldNo}</Text>
                {c.introEnd}
              </Text>
              {c.bullets.map((item, i) => (
                <View key={i} style={dStyles.bulletRow}>
                  <Text style={dStyles.bulletDot}>—</Text>
                  <Text style={dStyles.bulletText}>{item}</Text>
                </View>
              ))}
              <Text style={[dStyles.disclaimerBody, { marginTop: SPACING.md }]}>{c.footer}</Text>
            </View>

            <View style={dStyles.contextBlock}>
              <Text style={dStyles.contextHeading}>{c.aboutTitle}</Text>
              <Text style={dStyles.contextBody}>{c.aboutBody}</Text>
            </View>
          </ScrollView>

          <View style={dStyles.sheetFooter}>
            <TouchableOpacity style={dStyles.acceptButton} onPress={handleAccept}>
              <LinearGradient
                colors={['#C9A227', '#D4AF37', '#E8C840']}
                start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
                style={dStyles.acceptGradient}
              >
                <Text style={dStyles.acceptText}>{c.ctaButton}</Text>
              </LinearGradient>
            </TouchableOpacity>
            <Text style={dStyles.legalNote}>{c.ctaNote}</Text>
          </View>
        </Animated.View>
      </View>
    </Modal>
  );
}

// ─── InnerApp — has access to LanguageProvider ────────────────────────────────

function InnerApp() {
  const [appReady,       setAppReady]       = useState(false);
  const [showDisclaimer, setShowDisclaimer] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const accepted = await AsyncStorage.getItem(DISCLAIMER_KEY);
        if (!accepted) setShowDisclaimer(true);
        // TODO: await Font.loadAsync({ 'NotoSerifSC': require('./assets/fonts/NotoSerifSC-Regular.ttf') });
      } catch (e) {
        console.warn('[App] Prep error:', e);
      } finally {
        setAppReady(true);
        await SplashScreen.hideAsync().catch(() => {});
      }
    })();
  }, []);

  const handleDisclaimerAccept = useCallback(async () => {
    try { await AsyncStorage.setItem(DISCLAIMER_KEY, 'true'); } catch { /* silent */ }
    setShowDisclaimer(false);
  }, []);

  if (!appReady) return null;

  return (
    <NavigationContainer theme={NAV_THEME}>
      <StatusBar barStyle="light-content" backgroundColor={COLORS.background} />

      {/* Disclaimer gate — reads LanguageProvider to render in the correct language */}
      <DisclaimerModal visible={showDisclaimer} onAccept={handleDisclaimerAccept} />

      <Stack.Navigator
        screenOptions={{
          headerShown:  false,
          contentStyle: { backgroundColor: COLORS.background },
          animation:    'fade_from_bottom',
        }}
      >
        <Stack.Screen name="Home"    component={HomeScreen}    />
        <Stack.Screen name="Result"  component={ResultScreen}  />
        <Stack.Screen name="History" component={HistoryScreen} />
        <Stack.Screen name="Upgrade" component={UpgradeScreen} />
        <Stack.Screen name="About" component={AboutScreen} />
        <Stack.Screen name="Disclaimer" component={DisclaimerScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

// ─── Root export ──────────────────────────────────────────────────────────────
//
// LanguageProvider is the OUTERMOST React wrapper so every descendant —
// screens, modals, and future feature modules — can call useLanguage()
// or useText() without prop-drilling.
//
//  <LanguageProvider>        provides { language, isZh, toggleLanguage, … }
//    <InnerApp>              NavigationContainer + DisclaimerModal
//      <HomeScreen />        useText() for UI labels + LanguageToggle
//      <ResultScreen />      useText() for all hexagram field selection

export default function App() {
  return (
    <LanguageProvider>
      <InnerApp />
    </LanguageProvider>
  );
}

// ─── Disclaimer Styles ────────────────────────────────────────────────────────

const dStyles = StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.92)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: '#0D0D0D',
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    borderTopWidth: 1, borderColor: COLORS.goldDim,
    maxHeight: '88%',
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  sheetHeader: {
    alignItems: 'center', paddingTop: SPACING.xl, paddingBottom: SPACING.lg,
    borderBottomWidth: 1, borderBottomColor: COLORS.goldDim, paddingHorizontal: SPACING.lg,
  },
  sheetIcon:     { fontSize: 36, color: COLORS.gold, marginBottom: SPACING.sm },
  sheetTitle:    { fontFamily: FONTS.display, fontSize: 22, color: COLORS.gold, letterSpacing: 4, marginBottom: 4 },
  sheetSubtitle: { fontFamily: FONTS.caption, fontSize: 11, color: COLORS.textSecondary, letterSpacing: 3 },
  sheetScroll:   { paddingHorizontal: SPACING.lg, paddingTop: SPACING.lg },
  disclaimerBlock:    { marginBottom: SPACING.lg },
  disclaimerHeading:  { fontFamily: FONTS.caption, fontSize: 11, color: COLORS.changing, letterSpacing: 2, marginBottom: SPACING.sm },
  disclaimerBody:     { fontFamily: FONTS.body, fontSize: 14, color: COLORS.textSecondary, lineHeight: 22, marginBottom: SPACING.sm },
  disclaimerEmphasis: { color: COLORS.text, fontStyle: 'italic' },
  bulletRow:  { flexDirection: 'row', marginBottom: 6, paddingLeft: SPACING.sm },
  bulletDot:  { color: COLORS.goldMuted, marginRight: 10, fontFamily: FONTS.body, fontSize: 14 },
  bulletText: { fontFamily: FONTS.body, fontSize: 13, color: COLORS.textSecondary, flex: 1, lineHeight: 20 },
  contextBlock: {
    borderTopWidth: 1, borderTopColor: COLORS.goldDim,
    paddingTop: SPACING.lg, marginBottom: SPACING.xl,
  },
  contextHeading: { fontFamily: FONTS.caption, fontSize: 10, color: COLORS.goldMuted, letterSpacing: 3, marginBottom: SPACING.sm },
  contextBody:    { fontFamily: FONTS.body, fontSize: 13, color: COLORS.textSecondary, lineHeight: 21 },
  sheetFooter: {
    paddingHorizontal: SPACING.lg, paddingTop: SPACING.md,
    borderTopWidth: 1, borderTopColor: COLORS.goldDim,
  },
  acceptButton:   { borderRadius: 14, overflow: 'hidden', marginBottom: SPACING.sm },
  acceptGradient: { paddingVertical: 18, alignItems: 'center' },
  acceptText:     { fontFamily: FONTS.caption, fontSize: 14, color: '#000', letterSpacing: 2, fontWeight: '700' },
  legalNote: {
    fontFamily: FONTS.caption, fontSize: 9, color: COLORS.textSecondary,
    textAlign: 'center', letterSpacing: 0.5, opacity: 0.6, paddingBottom: SPACING.xs,
  },
});
