/**
 * screens/DisclaimerScreen.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Legal disclaimer screen — App Store / Play Store required.
 *
 * Contains:
 *   1. Entertainment-only notice
 *   2. No medical / legal / financial advice disclaimer
 *   3. Developer liability limitation
 *   4. Accuracy disclaimer
 *   5. Intellectual property notice
 *   6. Governing law reference
 *
 * Bilingual: English and Chinese, driven by useText() isZh flag.
 * Language toggle available so users can switch on this screen.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import React, { useRef, useEffect } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, Platform, Animated,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { useText } from '../context/LanguageContext';
import LanguageToggle from '../components/LanguageToggle';
import { COLORS, FONTS, SPACING } from '../constants/theme';

// ─── Disclaimer clause data ───────────────────────────────────────────────────
//
// Each clause has: number, titleEn, titleZh, bodyEn, bodyZh.
// Keeping data separate from render makes it easy to update legal copy
// without touching component logic.

const CLAUSES = [
  {
    num:     '01',
    titleEn: 'Entertainment Purposes Only',
    titleZh: '仅供娱乐',
    bodyEn:
      'This application, 易鉴 I-Ching Oracle, is designed strictly for entertainment, '
      + 'self-reflection, and personal enrichment. The divination readings, hexagram '
      + 'interpretations, and all related content are generated for exploratory and '
      + 'recreational purposes. They do not constitute factual predictions, '
      + 'professional counsel, or guaranteed outcomes of any kind.',
    bodyZh:
      '易鉴（I-Ching Oracle）应用程序严格设计用于娱乐、自我反思及个人成长之目的。'
      + '本应用中的占卜结果、卦象解读及所有相关内容，均仅供探索性娱乐使用，'
      + '不构成任何事实性预测、专业建议或任何形式的结果保证。',
  },
  {
    num:     '02',
    titleEn: 'No Professional Advice',
    titleZh: '非专业建议',
    bodyEn:
      'This app does not provide — and must not be relied upon as a substitute for — '
      + 'medical advice, psychological counselling, legal guidance, financial planning, '
      + 'or any other form of professional consultation. '
      + 'If you require professional assistance in any of these areas, please consult '
      + 'a qualified and licensed professional.',
    bodyZh:
      '本应用不提供且不得被视为可替代以下任何专业服务的内容：医疗建议、心理咨询、'
      + '法律指导、财务规划，或其他任何形式的专业咨询服务。'
      + '若您在上述任何领域需要专业帮助，请咨询具备相应资质的持证专业人员。',
  },
  {
    num:     '03',
    titleEn: 'Limitation of Liability',
    titleZh: '责任限制',
    bodyEn:
      'The developer, Daniel Liu, is not responsible for any decisions, actions, '
      + 'outcomes, losses, damages, or harm of any nature that arise directly or '
      + 'indirectly from the use of this application or reliance on its content. '
      + 'By using this app, you expressly acknowledge and accept that all decisions '
      + 'you make remain solely your own responsibility.',
    bodyZh:
      '开发者Daniel Liu对因使用本应用程序或依赖其内容而直接或间接引起的任何决策、行动、'
      + '后果、损失、损害或任何性质的伤害，不承担任何责任。'
      + '使用本应用即表示您明确认知并接受：您所做出的一切决定均由您本人独立承担全部责任。',
  },
  {
    num:     '04',
    titleEn: 'No Guarantee of Accuracy',
    titleZh: '不保证准确性',
    bodyEn:
      'I-Ching readings are based on classical Chinese philosophical texts and '
      + 'interpretive tradition. The outcomes generated by this application are '
      + 'probabilistic in nature and are in no way guaranteed to be accurate, '
      + 'predictive, or reflective of future events. Results may vary and should '
      + 'be treated as one perspective among many.',
    bodyZh:
      '易经占卜以中国古典哲学文本及传统诠释为基础。本应用所生成的占卜结果具有概率性质，'
      + '不以任何方式保证其准确性、预测性或对未来事件的反映。'
      + '结果可能因情境而异，应被视为众多参考角度之一，不应作为唯一判断依据。',
  },
  {
    num:     '05',
    titleEn: 'Intellectual Property',
    titleZh: '知识产权',
    bodyEn:
      'All original content within this application — including but not limited to '
      + 'the user interface design, written interpretations, bilingual translations, '
      + 'and software architecture — is the intellectual property of the developer '
      + 'and is protected under applicable copyright law. '
      + 'Classical I-Ching texts (Zhou Yi, 周易) are in the public domain.',
    bodyZh:
      '本应用内所有原创内容——包括但不限于用户界面设计、文字解读、双语翻译及软件架构——'
      + '均为开发者的知识产权，受相关版权法律保护。'
      + '《周易》等经典易经文本属于公共领域资料。',
  },
  {
    num:     '06',
    titleEn: 'User Responsibility',
    titleZh: '用户责任',
    bodyEn:
      'By using 易鉴, you confirm that you are 13 years of age or older '
      + '(or the minimum age required in your jurisdiction), and that you use '
      + 'this application voluntarily, understanding its entertainment nature. '
      + 'Do not use this application in situations requiring urgent, critical, '
      + 'or life-affecting decisions without appropriate professional guidance.',
    bodyZh:
      '使用易鉴即表示您确认您已年满13周岁（或您所在司法管辖区规定的最低年龄），'
      + '且您系自愿使用本应用，并了解其娱乐性质。'
      + '请勿在需要做出紧急、重要或影响人生重大决策的情况下，'
      + '在缺乏适当专业指导的前提下依赖本应用。',
  },
];

// ─── ClauseCard ───────────────────────────────────────────────────────────────

function ClauseCard({ clause, isZh, index }) {
  const slideAnim = useRef(new Animated.Value(20)).current;
  const fadeAnim  = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    const delay = 100 + index * 80;
    Animated.parallel([
      Animated.timing(fadeAnim,  { toValue: 1, duration: 350, delay, useNativeDriver: true }),
      Animated.spring(slideAnim, { toValue: 0, tension: 80, friction: 12, delay, useNativeDriver: true }),
    ]).start();
  }, []);

  return (
    <Animated.View
      style={[styles.clause, { opacity: fadeAnim, transform: [{ translateY: slideAnim }] }]}
    >
      {/* Clause number — decorative left accent */}
      <Text style={styles.clauseNum}>{clause.num}</Text>

      {/* Title */}
      <Text style={styles.clauseTitle}>
        {isZh ? clause.titleZh : clause.titleEn}
      </Text>

      {/* In zh mode always show the English title below as cross-reference */}
      {isZh && (
        <Text style={styles.clauseTitleRef}>{clause.titleEn}</Text>
      )}

      {/* Body */}
      <Text style={styles.clauseBody}>
        {isZh ? clause.bodyZh : clause.bodyEn}
      </Text>
    </Animated.View>
  );
}

// ─── DisclaimerScreen ─────────────────────────────────────────────────────────

export default function DisclaimerScreen() {
  const navigation = useNavigation();
  const { isZh }   = useText();

  // Hero entrance
  const heroFade  = useRef(new Animated.Value(0)).current;
  const heroSlide = useRef(new Animated.Value(-16)).current;

  useEffect(() => {
    Animated.parallel([
      Animated.timing(heroFade,  { toValue: 1, duration: 500, useNativeDriver: true }),
      Animated.spring(heroSlide, { toValue: 0, tension: 70, friction: 11, useNativeDriver: true }),
    ]).start();
  }, []);

  return (
    <View style={styles.container}>

      {/* ── Navbar ──────────────────────────────────────────────────────── */}
      <View style={styles.navbar}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.navBack}>
          <Text style={styles.navBackText}>← {isZh ? '返回' : 'Back'}</Text>
        </TouchableOpacity>

        <Text style={styles.navTitle}>
          {isZh ? '免责声明' : 'DISCLAIMER'}
        </Text>

        <LanguageToggle size="sm" />
      </View>

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        bounces
      >

        {/* ── Hero warning banner ────────────────────────────────────────── */}
        <Animated.View
          style={[styles.heroBanner, { opacity: heroFade, transform: [{ translateY: heroSlide }] }]}
        >
          <Text style={styles.heroIcon}>⚖</Text>
          <Text style={styles.heroTitle}>
            {isZh ? '重要声明' : 'Important Notice'}
          </Text>
          {/* The core one-liner — prominently displayed */}
          <View style={styles.heroAlert}>
            <Text style={styles.heroAlertText}>
              {isZh
                ? '本应用仅供娱乐目的，不提供医疗、法律或财务建议。\n开发者对基于本应用内容所做的任何决定概不负责。'
                : 'This app is for entertainment purposes only.\nIt does not provide medical, legal, or financial advice.\nThe developer is not responsible for any decisions made based on app readings.'}
            </Text>
          </View>
          <Text style={styles.heroEffectiveDate}>
            {isZh ? '生效日期：2026年1月1日' : 'Effective: January 1, 2026'}
          </Text>
        </Animated.View>

        {/* ── Clauses ────────────────────────────────────────────────────── */}
        {CLAUSES.map((clause, index) => (
          <ClauseCard
            key={clause.num}
            clause={clause}
            isZh={isZh}
            index={index}
          />
        ))}

        {/* ── Acceptance footer ──────────────────────────────────────────── */}
        <View style={styles.acceptanceBlock}>
          <View style={styles.acceptanceLine} />
          <Text style={styles.acceptanceText}>
            {isZh
              ? '继续使用本应用，即表示您已阅读、理解并同意以上所有条款。'
              : 'Continued use of this application constitutes your acknowledgement and acceptance of all terms stated above.'}
          </Text>
          <View style={styles.acceptanceLine} />
        </View>

        {/* ── Contact ────────────────────────────────────────────────────── */}
        <View style={styles.contactBlock}>
          <Text style={styles.contactText}>
            {isZh
              ? '如对本声明有任何疑问，请通过应用内"关于"页面联系开发者。'
              : 'For questions about this disclaimer, contact the developer via the About screen.'}
          </Text>
          <TouchableOpacity
            onPress={() => navigation.navigate('About')}
            style={styles.contactLink}
          >
            <Text style={styles.contactLinkText}>
              {isZh ? '前往关于页面 →' : 'Go to About →'}
            </Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    </View>
  );
}

// ─── Styles ────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },

  // ── Navbar
  navbar: {
    flexDirection:     'row',
    alignItems:        'center',
    justifyContent:    'space-between',
    paddingTop:        Platform.OS === 'ios' ? 56 : 36,
    paddingBottom:     12,
    paddingHorizontal: SPACING.lg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.goldDim,
    backgroundColor:   COLORS.background,
  },
  navBack:     { padding: 4, minWidth: 70 },
  navBackText: { fontFamily: FONTS.caption, fontSize: 13, color: COLORS.gold, letterSpacing: 0.5 },
  navTitle:    { fontFamily: FONTS.caption, fontSize: 11, color: COLORS.goldMuted, letterSpacing: 4 },

  // ── Scroll
  scrollContent: { paddingHorizontal: SPACING.lg, paddingBottom: 60 },

  // ── Hero banner — the most important content, above the fold
  heroBanner: {
    alignItems:    'center',
    paddingTop:    SPACING.xl,
    paddingBottom: SPACING.lg,
  },
  heroIcon: {
    fontSize:     32,
    color:        COLORS.changing,
    marginBottom: SPACING.sm,
  },
  heroTitle: {
    fontFamily:    FONTS.display,
    fontSize:      22,
    color:         COLORS.gold,
    letterSpacing: 3,
    marginBottom:  SPACING.md,
  },
  // Amber alert box — visually distinct, cannot be missed
  heroAlert: {
    backgroundColor: COLORS.changing + '18',
    borderRadius:    12,
    borderWidth:     1,
    borderColor:     COLORS.changing + '66',
    borderLeftWidth: 4,
    borderLeftColor: COLORS.changing,
    paddingVertical:   SPACING.md,
    paddingHorizontal: SPACING.lg,
    marginBottom:      SPACING.md,
    width:             '100%',
  },
  heroAlertText: {
    fontFamily: FONTS.body,
    fontSize:   14,
    color:      COLORS.text,
    lineHeight: 22,
    textAlign:  'center',
  },
  heroEffectiveDate: {
    fontFamily:    FONTS.caption,
    fontSize:      9,
    color:         COLORS.textSecondary,
    letterSpacing: 1,
    opacity:       0.5,
  },

  // ── Clause cards
  clause: {
    backgroundColor: COLORS.surface,
    borderRadius:    14,
    borderWidth:     1,
    borderColor:     COLORS.goldDim,
    padding:         SPACING.lg,
    marginBottom:    SPACING.md,
  },
  clauseNum: {
    fontFamily:    FONTS.caption,
    fontSize:      9,
    color:         COLORS.goldDim,
    letterSpacing: 3,
    marginBottom:  SPACING.xs,
    opacity:       0.6,
  },
  clauseTitle: {
    fontFamily:    FONTS.display,
    fontSize:      16,
    color:         COLORS.gold,
    letterSpacing: 1,
    marginBottom:  4,
    lineHeight:    22,
  },
  clauseTitleRef: {
    fontFamily:    FONTS.bodyItalic ?? FONTS.body,
    fontSize:      11,
    color:         COLORS.textSecondary,
    letterSpacing: 0.3,
    marginBottom:  SPACING.sm,
    opacity:       0.6,
    fontStyle:     'italic',
  },
  clauseBody: {
    fontFamily: FONTS.body,
    fontSize:   13,
    color:      COLORS.textSecondary,
    lineHeight: 21,
    marginTop:  SPACING.sm,
  },

  // ── Acceptance footer
  acceptanceBlock: {
    alignItems:   'center',
    marginTop:    SPACING.sm,
    marginBottom: SPACING.lg,
    paddingHorizontal: SPACING.md,
  },
  acceptanceLine: {
    width:           48,
    height:          1,
    backgroundColor: COLORS.goldDim,
    opacity:         0.4,
    marginVertical:  SPACING.sm,
  },
  acceptanceText: {
    fontFamily:    FONTS.body,
    fontSize:      12,
    color:         COLORS.textSecondary,
    textAlign:     'center',
    lineHeight:    19,
    opacity:       0.75,
  },

  // ── Contact block
  contactBlock: {
    alignItems:   'center',
    paddingBottom: SPACING.xl,
    gap:           SPACING.sm,
  },
  contactText: {
    fontFamily:  FONTS.caption,
    fontSize:    10,
    color:       COLORS.textSecondary,
    textAlign:   'center',
    letterSpacing: 0.3,
    opacity:     0.5,
    lineHeight:  16,
  },
  contactLink: {
    borderWidth:      1,
    borderColor:      COLORS.goldDim,
    borderRadius:     8,
    paddingVertical:  7,
    paddingHorizontal: SPACING.md,
  },
  contactLinkText: {
    fontFamily:    FONTS.caption,
    fontSize:      11,
    color:         COLORS.goldMuted,
    letterSpacing: 0.5,
  },
});
